#cloud-config

packages:
  - nginx
  - libnginx-mod-http-fancyindex
  - apache2-utils

write_files:
  - content: |
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;
        location / {
          autoindex on;
          # First attempt to serve request as file, then
          # as directory, then fall back to displaying a 404.
          try_files $uri $uri/ =404;
          auth_basic "Restricted Content";
          auth_basic_user_file /etc/nginx/.htpasswd;
        }
      }
    path: /etc/nginx/sites-available/default

runcmd:
  - rm -f /var/www/html/*.html
  - htpasswd -b -c /etc/nginx/.htpasswd ${username} ${password}
